---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-6.4

suites:
  - name: base
    run_list:
      - recipe[esha-roles::base]
    attributes:
  - name: client
    run_list:
      - recipe[esha-roles::client]
    attributes:
